### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by amjo** [rchavik/AdminExtras#1]
sorry for the newbie question, but i tried uploading it, and didn't work. also i tried placing it under Plugins, and didn't show up in the Extensions->plugins page 

_feeling dumb_

croogo 2.2.3

**Comment by rchavik** [comment]
This is for cake 2.x, so it goes under `APP/View/Themed/AdminExtras`.

Then activate it by running 

```
cd $APP
Console/cake settings.settings write Site.admin_theme AdminExtras
```
